
version: "3.7"

services:
  vscode:
    build: .
    ports:
      - "554:554/udp"
      - "10080:10080/udp"
      - "10081:10081/udp"
    volumes:
      - ../:/workspace
      - ~/.docker:/home/vscode/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: zsh -c "while sleep 1000; do :; done"

